Repository MolSSI/QCElemental, pull requests merged in 2019-09, with the labels that each got.

#125 catch dropped atoms early again
  qcelemental/molparse/from_arrays.py
  qcelemental/molparse/from_schema.py
Labels: Enhancement

#132 Model BasisSet and Result documentation
  qcelemental/__init__.py
  qcelemental/covalent_radii.py
  qcelemental/models/__init__.py
  qcelemental/models/basis.py
  qcelemental/models/common_models.py
  qcelemental/models/molecule.py
  qcelemental/models/procedures.py
  qcelemental/models/results.py
  qcelemental/molparse/to_string.py
  qcelemental/physical_constants/context.py
  qcelemental/testing.py
  qcelemental/tests/test_models_basis.py
  qcelemental/vanderwaals_radii.py
Labels: Documentation, Enhancement

#141 Models: Force skip defaults for protocols
  qcelemental/models/basis.py
  qcelemental/models/procedures.py
  qcelemental/models/results.py
Labels: Enhancement

#142 Update change log for 0.9.0 and add GitHub Templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  docs/source/changelog.rst
Labels: Documentation
