Repository MolSSI/QCElemental, pull requests merged in 2019-10, with the labels that each got.

#146 Finalize changelog for 0.10.0
  docs/source/changelog.rst
Labels: Documentation

#148 NGLView Integration
  devtools/conda-envs/base.yaml
  docs/source/molecule.rst
  qcelemental/models/molecule.py
  qcelemental/molparse/to_string.py
  qcelemental/molutil/__init__.py
  qcelemental/molutil/connectivity.py
  qcelemental/molutil/test_molutil.py
  qcelemental/tests/addons.py
  qcelemental/tests/test_molecule.py
  qcelemental/tests/test_molparse_to_string.py
  setup.py
Labels: Feature

#147 Pydantic 1.0 Changes
  devtools/conda-envs/base.yaml
  devtools/conda-envs/minimal_pins.yaml
  qcelemental/datum.py
  qcelemental/models/align.py
  qcelemental/models/basemodels.py
  qcelemental/models/basis.py
  qcelemental/models/common_models.py
  qcelemental/models/molecule.py
  qcelemental/models/procedures.py
  qcelemental/models/results.py
  qcelemental/physical_constants/context.py
  qcelemental/tests/test_model_results.py
  qcelemental/tests/test_model_serials.py
  qcelemental/tests/test_molecule.py
  qcelemental/tests/test_utils.py
  qcelemental/util/autodocs.py
  qcelemental/util/gph_uno_bipartite.py
  setup.py
Labels: Enhancement

#149 Units: Adds debye
  qcelemental/physical_constants/ureg.py
  qcelemental/tests/test_units.py
Labels: Enhancement

#151 v11 Changelog and Docs
  docs/source/changelog.rst
  docs/source/index.rst
  docs/source/model_common.rst
  docs/source/model_molecule.rst
  docs/source/model_result.rst
  docs/source/periodic_table.rst
  docs/source/vanderwaals_radii.rst
  qcelemental/covalent_radii.py
  qcelemental/models/basis.py
  qcelemental/models/common_models.py
  qcelemental/models/results.py
  qcelemental/vanderwaals_radii.py
Labels: Documentation
