Repository MolSSI/QCElemental, pull requests merged in 2019-08, with the labels that each got.

#86 Molecule validation performance improvements
  qcelemental/models/basemodels.py
  qcelemental/models/molecule.py
  qcelemental/molparse/chgmult.py
  qcelemental/molparse/from_arrays.py
  qcelemental/molparse/from_schema.py
  qcelemental/molparse/nucleus.py
  qcelemental/molparse/to_schema.py
  qcelemental/molparse/to_string.py
  qcelemental/physical_constants/context.py
  qcelemental/tests/addons.py
  qcelemental/tests/test_model_serials.py
  qcelemental/tests/test_molparse_from_string.py
  qcelemental/tests/test_molparse_pubchem.py
  qcelemental/tests/test_molparse_to_schema.py
Labels: Enhancement

#88 Port Fractal Autodoc to Elemental, Autodoc Molecule Object
  docs/source/molecule.rst
  qcelemental/__init__.py
  qcelemental/models/molecule.py
  qcelemental/tests/test_utils.py
  qcelemental/util/__init__.py
  qcelemental/util/autodocs.py
Labels: Documentation, Enhancement

#87 Pydantic Bump
  .codecov.yml
  devtools/conda-envs/base.yaml
  devtools/conda-envs/minimal_pins.yaml
  docs/source/models.rst
  qcelemental/__init__.py
  qcelemental/data/__init__.py
  qcelemental/models/__init__.py
  qcelemental/models/align.py
  qcelemental/models/basemodels.py
  qcelemental/models/common_models.py
  qcelemental/models/molecule.py
  qcelemental/models/results.py
  qcelemental/molparse/__init__.py
  qcelemental/molparse/from_arrays.py
  qcelemental/molparse/from_string.py
  qcelemental/molparse/nucleus.py
  qcelemental/molutil/__init__.py
  qcelemental/molutil/align.py
  qcelemental/molutil/test_align.py
  qcelemental/physical_constants/__init__.py
  qcelemental/physical_constants/context.py
  qcelemental/testing.py
  qcelemental/tests/addons.py
  qcelemental/tests/test_model_serials.py
  qcelemental/tests/test_molecule.py
  qcelemental/tests/test_utils.py
  qcelemental/util/__init__.py
  qcelemental/util/gph_uno_bipartite.py
  qcelemental/util/serialization.py
  qcelemental/util/test_gph_uno_bipartite.py
  qcelemental/util/test_scipy_hungarian.py
  setup.py
Labels: Enhancement

#114 NumPy: Calls top level functions and not core C functions
  qcelemental/molparse/from_arrays.py
Labels: Bug

#115 Cherry-pick for 0.6.1: NumPy: Calls top level functions and not core C functions
  docs/source/changelog.rst
  qcelemental/molparse/from_arrays.py
Labels: Bug

#116 Update master docs for 0.6.1
  docs/source/changelog.rst
Labels: Documentation

#117 Better install instructions
  docs/source/install.rst
Labels: Documentation

#120 Autodocs on ProtoModel
  docs/source/api.rst
  docs/source/community.rst
  docs/source/covalent_radii.rst
  docs/source/index.rst
  docs/source/molecule.rst
  qcelemental/covalent_radii.py
  qcelemental/models/basemodels.py
  qcelemental/models/molecule.py
  qcelemental/molparse/to_string.py
  qcelemental/util/autodocs.py
Labels: Enhancement

#118 Models Repr
  qcelemental/models/basemodels.py
  qcelemental/models/common_models.py
  qcelemental/models/molecule.py
  qcelemental/models/procedures.py
  qcelemental/models/results.py
  qcelemental/tests/test_model_serials.py
Labels: Enhancement

#119 more options from to_string()
  qcelemental/models/molecule.py
  qcelemental/molparse/to_string.py
Labels: Enhancement

#121 YAPF'd, isort'd, changelog'd: 0.7.0 Release
  .yapfignore
  docs/source/changelog.rst
  nist_data/build_periodic_table.py
  nist_data/build_physical_constants.py
  qcelemental/__init__.py
  qcelemental/checkup_data/__init__.py
  qcelemental/checkup_data/periodictable.py
  qcelemental/covalent_radii.py
  qcelemental/data/alvarez_2008_covalent_radii.py
  qcelemental/exceptions.py
  qcelemental/models/__init__.py
  qcelemental/models/align.py
  qcelemental/models/basemodels.py
  qcelemental/models/common_models.py
  qcelemental/molparse/chgmult.py
  qcelemental/molparse/from_arrays.py
  qcelemental/molparse/from_schema.py
  qcelemental/molparse/from_string.py
  qcelemental/molparse/pubchem.py
  qcelemental/molparse/to_schema.py
  qcelemental/molutil/test_align.py
  qcelemental/periodic_table.py
  qcelemental/physical_constants/context.py
  qcelemental/physical_constants/ureg.py
  qcelemental/testing.py
  qcelemental/tests/test_molparse_align_chiral.py
  qcelemental/tests/test_molparse_from_string.py
  qcelemental/tests/test_molparse_to_schema.py
  qcelemental/tests/test_units.py
  qcelemental/tests/test_utils.py
  qcelemental/util/autodocs.py
  qcelemental/util/importing.py
  qcelemental/util/misc.py
  qcelemental/util/np_rand3drot.py
  qcelemental/util/scipy_hungarian.py
  qcelemental/util/test_gph_uno_bipartite.py
  qcelemental/util/test_scipy_hungarian.py
  setup.cfg
Labels: Documentation
