Repository MolSSI/QCElemental, pull requests merged in 2019-03, with the labels that each got.

#37 QCA Sphinx Theme
  docs/requirements.yml
  docs/source/conf.py
  qcelemental/models/__init__.py
  qcelemental/models/results.py
Labels: Documentation

#39 make `python setup.py test` work
  setup.cfg
  setup.py
Labels: Enhancement, Testing

#46 Periodic Table Docs
  docs/source/index.rst
  docs/source/install.rst
  docs/source/models.rst
  docs/source/molecule.rst
  docs/source/periodic_table.rst
  docs/source/physconst.rst
  qcelemental/physical_constants/context.py
Labels: Documentation

#48 Molecule: Prevent duplicate validates
  docs/source/changelog.rst
  qcelemental/models/molecule.py
  qcelemental/tests/test_molecule.py
Labels: Enhancement

#50 License: Standardization MolSSI/QCA authors
  docs/source/conf.py
  setup.py
Labels: Documentation

#51 Molecule: Changes default connectivity to None.
  qcelemental/models/molecule.py
  qcelemental/tests/test_molecule.py
Labels: Bug, Enhancement
